create table STUDENT
(
    STUDENT_ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    EMAIL_VERIFIED BOOLEAN NOT NULL,
    EMAIL_VERIFICATION_CODE VARCHAR(5),
    GRADUATION_YEAR INT
);
