INSERT INTO STUDENT (NAME, EMAIL, EMAIL_VERIFIED, GRADUATION_YEAR) VALUES ('Wayne', 'wayne@aol.com', false, null);
INSERT INTO STUDENT (NAME, EMAIL, EMAIL_VERIFIED, GRADUATION_YEAR) VALUES ('Mark', 'mark77@hotmail.com', false, 2012);
INSERT INTO STUDENT (NAME, EMAIL, EMAIL_VERIFIED, GRADUATION_YEAR) VALUES ('Connor', 'mcjesus@gmail.com', false, 2002);
INSERT INTO STUDENT (NAME, EMAIL, EMAIL_VERIFIED, GRADUATION_YEAR) VALUES ('Jari', 'jarijari@outlook.com', false, 2009);
